PROGRAMS=allcaps cut_paste editor error_test file_browser modify_text password prompt_phone prompt_phone2 replace search_text select_text simple_text text_box

CFLAGS=
LIBS= -lXm -lXt -lX11

all: $(PROGRAMS)

.c: ; $(CC) $(CFLAGS) $@.c $(LIBS) -o $@
