# ##########################################################
#
#  Makefile SunOS5 (Solaris) pour applications Motif
#  E. Lecolinet - ENST - Dec 1995
#
# ##########################################################

# ##########################################################
#
# Remarques
#
# -1- pour savoir la version du systeme d'exploitation
#     taper la commande:   uname -r
#     Le PREMIER chiffre indique la version de SunOS
#     (systeme "Solaris" = SunOS5)
#
# -2- pour utiliser ce Makefile, taper:
#     make  -f Makefile.SunOS5  nom-de-l'executable-a-creer
# ou
#     faire:   ln  Makefile.SunOS5  Makefile
#     puis :   make  nom-de-l'executable-a-creer
#     (par defaut, make utilise le fichier "Makefile")

# ##########################################################
#
# Emplacement des Librairies X et Motif
#
XDIR = /usr/X11R5

# ##########################################################
#
# KEEP_STATE => verification automatique des dependances
# et des options de compilation (ne PAS faire "make depend")
#
.KEEP_STATE:

# ##########################################################
#
# Compilation

# compilateur (de preference ANSI C)
CC = gcc

# rajouter la ligne suivante si le compilateur n'est pas ANSI
# CFLAGS += -D_NO_PROTO

# emplacement des headers X et Motif
CFLAGS += -I${XDIR}/include

# options de compilation:
# - l'option -g est necessaire pour utiliser le debugger
# - l'option -O permet d'optimiser l'executable
CFLAGS += -g

# ##########################################################
#
# Edition de Liens

# options:
# -L sert a specifie le repertoire des librairies a l'EDITION DE LIENS
# -R sert a specifie le repertoire des librairies a l'EXECUTION
#   ( ! Attention: l'option -R n'existe pas sous SunOS4 ! )
# Note:
#   En absence d'option -R, les librairies utilisee a l'execution
#   sont cherchees dans les repertoires indiques par LD_LIBRARY_PATH
#   ==> sans option -R, le programme plantera a l'EXECUTION si ces
#   repertoires sont incorrects ou ne figurent pas dans le bon ordre

LDLIBS = -L${XDIR}/lib -R${XDIR}/lib -lXm -lXt -lX11 -lsocket -lnsl -lgen -lm

# ##########################################################
#
# Regles

# pas de regle explicite => taper: 
#    make  -f Makefile.SunOS4  nom-de-l'executable-a-creer
#
# (ou completer ce Makefile en rajoutant les regles de
# production adequates)
