PROGRAMS=attach corners entry_cb form_corners frame paned_win1 paned_win2 proc_traversal rowcol spreadsheet text_entry text_form tictactoe traversal unit_types

CFLAGS=
LIBS= -lXm -lXt -lX11

all: $(PROGRAMS)

.c: ; $(CC) $(CFLAGS) $@.c $(LIBS) -o $@
