PROGRAMS=showuid trivial.uid kids.uid resource.uid cb.uid first.uid second.uid multiline.uid joel.uid bomb.uid globe.uid simple_lst.uid station.uid

CFLAGS=
LIBS= -lMrm -lXm -lXt -lX11

.SUFFIXES : .uil .uid

all: $(PROGRAMS)

.c: ; $(CC) $(CFLAGS) $@.c $(LIBS) -o $@

.uil.uid: ; uil -o $@ $<
